language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
sudo: false
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/conda
  - export PATH="$HOME/conda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda create -q -n molvs python=$TRAVIS_PYTHON_VERSION
  - conda env update -q -n molvs -f environment.yml
  - source activate molvs
  - conda install -q coverage coveralls pytest-cov
  - python setup.py install
script:
  - pytest --cov=molvs tests
after_success:
  - coveralls
